"use client";

import { useEffect, useRef, useState } from "react";
import { mockAdminSettlements, settlementAmounts, settlementSummary, settlementsCsv, simulatePayout, type Settlement } from "@/data/admin/mockAdminPayments";
import { formatRupees } from "@/data/admin/mockAdmin";
import { bookingDate } from "@/data/admin/mockAdminBookings";
import { AdminPageHeader } from "./admin-page-header";
import { AdminIcon } from "./admin-icon";
import { PayoutConfirmation, payoutButton, payoutPrimary } from "./admin-payout-confirmation";

const control = "min-h-10 rounded-full border border-neutral-200 bg-white px-4 text-xs text-neutral-600 focus-visible:outline-2 focus-visible:outline-neutral-800";
const pageSize = 10;
function SelectAll({ checked, mixed, onChange }: { checked: boolean; mixed: boolean; onChange: () => void }) {
  const ref = useRef<HTMLInputElement>(null);
  useEffect(() => { if (ref.current) ref.current.indeterminate = mixed; }, [mixed]);
  return <input ref={ref} type="checkbox" aria-label="Select all visible settlements" checked={checked} onChange={onChange} className="size-4 accent-neutral-900" />;
}
function Badge({ status }: { status: Settlement["status"] }) { return <span className={`rounded-full border px-2 py-1 text-[9px] font-semibold ${status === "PAID" ? "border-neutral-800 bg-neutral-800 text-white" : "border-neutral-200 bg-neutral-50 text-neutral-600"}`}>{status}</span>; }
export function AdminPayments() {
  const [settlements, setSettlements] = useState(mockAdminSettlements);
  const [tab, setTab] = useState<"pending" | "history">("pending");
  const [venue, setVenue] = useState(""); const [status, setStatus] = useState<"" | Settlement["status"]>("PENDING");
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [dateOpen, setDateOpen] = useState(false);
  const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]);
  const [confirmIds, setConfirmIds] = useState<string[] | null>(null); const [notice, setNotice] = useState("");
  const summary = settlementSummary(settlements);
  const venues = Array.from(new Map(settlements.map(item => [item.venueId, item.venueName])).entries());
  const invalidDates = Boolean(from && to && from > to);
  const filtered = settlements.filter(item => {
    const date = tab === "history" ? item.payoutDate ?? "" : item.settlementDate;
    return item.status === (tab === "pending" ? "PENDING" : "PAID") && (!venue || item.venueId === venue) && (!status || item.status === status) && !invalidDates && (!from || date >= from) && (!to || date <= to);
  });
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, pages);
  const start = (currentPage - 1) * pageSize; const visible = filtered.slice(start, start + pageSize);
  const selectedRows = visible.filter(item => item.status === "PENDING" && selected.includes(item.id));
  const confirming = settlements.filter(item => confirmIds?.includes(item.id) && item.status === "PENDING");
  function resetPage() { setPage(1); setSelected([]); }
  function changeTab(next: typeof tab) { setTab(next); setStatus(next === "pending" ? "PENDING" : "PAID"); resetPage(); }
  function resetFilters() { setVenue(""); setStatus(tab === "pending" ? "PENDING" : "PAID"); setFrom(""); setTo(""); resetPage(); }
  function exportReport() { const url = URL.createObjectURL(new Blob(["\uFEFF", settlementsCsv(filtered)], { type: "text/csv;charset=utf-8;" })); const link = document.createElement("a"); link.href = url; link.download = `arenax-${tab}-payouts.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice(`Exported ${filtered.length} settlements.`); }
  function confirmPayout() {
    const ids = new Set(confirming.map(item => item.id));
    const date = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
    setSettlements(current => current.map(item => ids.has(item.id) ? simulatePayout(item, date) : item));
    setNotice(`${ids.size} payout${ids.size === 1 ? "" : "s"} marked paid in this preview. View Payout History for the reference. No money was transferred.`); setSelected([]); setConfirmIds(null);
  }
  return <>
    <AdminPageHeader title="Payments" subtitle="Manage manager settlements and platform earnings"><button type="button" disabled={!filtered.length} onClick={exportReport} className={payoutPrimary}><AdminIcon name="export" />Export Report</button></AdminPageHeader>
    <dl aria-label="Payment summary" className="grid gap-5 md:grid-cols-3">{[{ label: "TOTAL REVENUE COLLECTED", value: summary.revenue, icon: "payments" as const }, { label: "PLATFORM COMMISSION EARNED", value: summary.commission, icon: "arrow" as const }, { label: "PENDING PAYOUTS", value: summary.pending, icon: "clock" as const }].map((stat, index) => <div key={stat.label} className="flex min-w-0 items-center gap-4 rounded-xl border border-neutral-100 bg-white p-5 shadow-xs"><span className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-neutral-100 text-neutral-600"><AdminIcon name={stat.icon} className="size-5" /></span><div className="min-w-0"><dt className="text-[10px] font-semibold tracking-wider text-neutral-400">{stat.label}</dt><dd className="mt-1 text-xl font-bold tabular-nums break-words">{formatRupees(stat.value)}</dd>{index === 2 && <p className="mt-1 text-[10px] text-neutral-500">{summary.waiting} managers waiting</p>}</div></div>)}</dl>
    <div role="group" aria-label="Payout tabs" className="mt-6 flex gap-6 border-b border-neutral-200">{([['pending', 'Pending Payouts'], ['history', 'Payout History']] as const).map(([value, label]) => <button id={value === "pending" ? "pending-payouts-tab" : undefined} key={value} type="button" aria-pressed={tab === value} onClick={() => changeTab(value)} className={`border-b-2 px-1 py-4 text-sm font-semibold focus-visible:outline-2 ${tab === value ? "border-neutral-900 text-neutral-900" : "border-transparent text-neutral-400 hover:text-black"}`}>{label}</button>)}</div>
    <section aria-label="Settlement filters" className="my-4 space-y-3"><div className="flex flex-wrap items-center gap-3"><select aria-label="Venue" value={venue} onChange={event => { setVenue(event.target.value); resetPage(); }} className={`${control} max-w-full`}><option value="">Venue: All</option>{venues.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="Status" value={status} onChange={event => { const next = event.target.value as typeof status; setStatus(next); if (next) setTab(next === "PENDING" ? "pending" : "history"); resetPage(); }} className={control}><option value="">Status: All in this tab</option><option value="PENDING">Status: Pending</option><option value="PAID">Status: Paid</option></select><button type="button" aria-expanded={dateOpen} aria-controls="payout-date-range" onClick={() => setDateOpen(!dateOpen)} className={`${control} flex items-center gap-2`}><AdminIcon name="bookings" />Date Range{from || to ? " · Active" : ""}</button><button type="button" aria-label="Reset settlement filters" onClick={resetFilters} className={`${control} flex items-center`}><AdminIcon name="refresh" /></button>{selectedRows.length > 0 && <button type="button" onClick={() => setConfirmIds(selectedRows.map(item => item.id))} className={payoutPrimary}>Process Selected ({selectedRows.length})</button>}</div>{dateOpen && <div id="payout-date-range" className="flex flex-wrap items-end gap-3 rounded-xl border border-neutral-200 bg-white p-4"><label className="grid gap-1 text-xs text-neutral-500">From<input aria-label="Settlement from date" type="date" value={from} onChange={event => { setFrom(event.target.value); resetPage(); }} className={control} /></label><label className="grid gap-1 text-xs text-neutral-500">To<input aria-label="Settlement to date" type="date" value={to} onChange={event => { setTo(event.target.value); resetPage(); }} className={control} /></label><button type="button" onClick={() => { setFrom(""); setTo(""); resetPage(); }} className={control}>Clear dates</button><p className="pb-3 text-xs text-neutral-500">{tab === "pending" ? "Settlement" : "Payout"} date · Includes both dates.</p></div>}{invalidDates && <p role="alert" className="text-sm">Choose an end date on or after the start date.</p>}</section>
    <section aria-label="Settlements" className="rounded-xl border border-neutral-200 bg-white shadow-xs"><div className="overflow-x-auto rounded-t-xl"><table className={`w-full text-left text-xs ${tab === "pending" ? "min-w-[1200px]" : "min-w-[1050px]"}`}><thead className="bg-neutral-50 text-[10px] tracking-wide text-neutral-400 uppercase"><tr>{tab === "pending" && <th scope="col" className="px-5 py-5"><SelectAll checked={visible.length > 0 && selectedRows.length === visible.length} mixed={selectedRows.length > 0 && selectedRows.length < visible.length} onChange={() => setSelected(selectedRows.length === visible.length ? [] : visible.map(item => item.id))} /></th>}{(tab === "pending" ? ["Manager & Venue", "Total Bookings", "Gross Amount", "Commission %", "Commission Amount", "Net Payable", "Bank Account", "Status", "Actions"] : ["Manager & Venue", "Gross Amount", "Commission", "Net Paid", "Bank Account", "Payout Date", "Reference ID", "Status"]).map(label => <th key={label} scope="col" className="px-4 py-5 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{visible.map(item => {
      const amounts = settlementAmounts(item.grossAmount, item.commissionPercentage);
      return <tr key={item.id} aria-label={`Settlement ${item.id}`} className={selected.includes(item.id) && tab === "pending" ? "bg-neutral-100" : "hover:bg-neutral-50"}>{tab === "pending" && <td className="px-5 py-5"><input type="checkbox" aria-label={`Select ${item.id}`} checked={selected.includes(item.id)} onChange={() => setSelected(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} className="size-4 accent-neutral-900" /></td>}<th scope="row" className="px-4 py-5"><div className="flex items-center gap-3"><span aria-hidden="true" className="flex size-9 shrink-0 items-center justify-center rounded-full bg-neutral-200 text-[10px] font-semibold text-neutral-600">{item.managerName.split(" ").map(part => part[0]).join("").slice(0,2)}</span><div className="min-w-24"><p className="font-semibold">{item.managerName}</p><p className="mt-1 text-[10px] font-normal text-neutral-400">{item.venueName}</p></div></div></th>{tab === "pending" && <td className="px-4 py-5 text-center font-semibold">{item.totalBookings}</td>}<td className="px-4 py-5 whitespace-nowrap text-neutral-600">{formatRupees(item.grossAmount)}</td>{tab === "pending" && <td className="px-4 py-5 text-neutral-400">{item.commissionPercentage}%</td>}<td className="px-4 py-5 whitespace-nowrap text-neutral-500">{formatRupees(amounts.commissionAmount)}</td><td className="px-4 py-5 font-semibold whitespace-nowrap">{formatRupees(amounts.netPayable)}</td><td className="px-4 py-5 font-mono whitespace-nowrap text-neutral-400">•••• {item.bankLast4}</td>{tab === "history" && <><td className="px-4 py-5 text-neutral-500">{item.payoutDate ? bookingDate(item.payoutDate) : "—"}</td><td className="px-4 py-5 font-mono text-[10px] text-neutral-500">{item.referenceId}</td></>}<td className="px-4 py-5"><Badge status={item.status} /></td>{tab === "pending" && <td className="px-4 py-5"><button type="button" aria-label={`Process payout ${item.id}`} onClick={() => setConfirmIds([item.id])} className={`${payoutPrimary} whitespace-nowrap`}>Process Payout</button></td>}</tr>;
    })}</tbody></table></div>{!filtered.length && <div className="p-12 text-center"><h2 className="font-semibold">No settlements found</h2><p className="mt-2 text-sm text-neutral-500">Try adjusting your filters or switching tabs.</p><button type="button" onClick={resetFilters} className={`${payoutButton} mt-4`}>Reset filters</button></div>}<div className="flex flex-wrap items-center justify-between gap-3 border-t border-neutral-100 p-4"><p role="status" className="text-xs text-neutral-500">Showing {filtered.length ? start + 1 : 0}–{Math.min(start + pageSize, filtered.length)} of {filtered.length} settlements</p><nav aria-label="Settlement pagination" className="flex gap-1"><button type="button" aria-label="Previous page" disabled={currentPage === 1} onClick={() => { setPage(currentPage - 1); setSelected([]); }} className={`${payoutButton} disabled:opacity-30`}>‹</button>{Array.from({ length: pages }, (_, index) => index + 1).map(number => <button type="button" key={number} aria-label={`Page ${number}`} aria-current={number === currentPage ? "page" : undefined} onClick={() => { setPage(number); setSelected([]); }} className={number === currentPage ? payoutPrimary : payoutButton}>{number}</button>)}<button type="button" aria-label="Next page" disabled={currentPage === pages} onClick={() => { setPage(currentPage + 1); setSelected([]); }} className={`${payoutButton} disabled:opacity-30`}>›</button></nav></div></section>
    <p role="status" className="mt-3 text-xs text-neutral-600">{notice}</p><p className="mt-2 text-xs text-neutral-500">Mock settlement snapshots · Changes last until you leave or reload. No real payments are processed.</p>
    {confirmIds && confirming.length > 0 && <PayoutConfirmation settlements={confirming} onClose={() => setConfirmIds(null)} onConfirm={confirmPayout} />}
  </>;
}
