"use client";

import { useEffect, useRef } from "react";
import { type Settlement, settlementAmounts } from "@/data/admin/mockAdminPayments";
import { formatRupees } from "@/data/admin/mockAdmin";
import { AdminIcon } from "./admin-icon";
export const payoutButton = "inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-neutral-200 px-4 text-xs font-semibold hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-40";
export const payoutPrimary = `${payoutButton} border-neutral-900 bg-neutral-900 text-white hover:bg-black`;
export function PayoutConfirmation({ settlements, onClose, onConfirm }: { settlements: Settlement[]; onClose: () => void; onConfirm: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {
    const element = ref.current; const previous = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; element?.showModal();
    return () => { element?.close(); document.body.style.overflow = overflow; if (previous?.isConnected) previous.focus(); else document.getElementById("pending-payouts-tab")?.focus(); };
  }, []);
  const total = settlements.reduce((sum, item) => sum + Math.round(settlementAmounts(item.grossAmount, item.commissionPercentage).netPayable * 100), 0) / 100;
  return <dialog ref={ref} aria-labelledby="payout-confirm-title" onCancel={onClose} onClose={event => { if (!event.currentTarget.open) onClose(); }} onClick={event => { if (event.target !== event.currentTarget) return; const bounds = event.currentTarget.getBoundingClientRect(); if (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom) onClose(); }} className="fixed inset-0 m-auto max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] max-w-lg overflow-y-auto rounded-2xl border border-neutral-200 bg-white p-0 text-neutral-900 shadow-2xl backdrop:bg-black/40"><header className="flex items-center justify-between border-b border-neutral-100 px-6 py-4"><h2 id="payout-confirm-title" className="text-lg font-semibold">{settlements.length > 1 ? "Process selected payouts?" : "Process payout?"}</h2><button type="button" aria-label="Close payout confirmation" onClick={onClose} className="flex size-9 items-center justify-center rounded-lg hover:bg-neutral-100 focus-visible:outline-2"><AdminIcon name="close" /></button></header><div className="space-y-4 p-6"><p className="text-sm text-neutral-500">This marks the selected settlement{settlements.length === 1 ? "" : "s"} as paid in this preview. No money will be transferred.</p>{settlements.map(item => { const amounts = settlementAmounts(item.grossAmount, item.commissionPercentage); return <section key={item.id} aria-label={item.id} className="rounded-xl border border-neutral-200 p-4"><h3 className="text-sm font-semibold">{item.managerName}</h3><p className="mt-1 text-xs text-neutral-500">{item.venueName} · {item.id}</p><dl className="mt-4 grid grid-cols-2 gap-4">{[["Gross Amount", formatRupees(item.grossAmount)], [`Commission (${item.commissionPercentage}%)`, formatRupees(amounts.commissionAmount)], ["Net Payable", formatRupees(amounts.netPayable)], ["Bank Account", `•••• ${item.bankLast4}`]].map(([label, value]) => <div key={label}><dt className="text-[10px] text-neutral-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>)}</dl></section>; })}<p className="text-right text-sm font-semibold">Total net payable: {formatRupees(total)}</p></div><footer className="sticky bottom-0 flex justify-end gap-3 border-t border-neutral-100 bg-white p-5"><button autoFocus type="button" onClick={onClose} className={payoutButton}>Cancel</button><button type="button" onClick={onConfirm} className={payoutPrimary}>Confirm Payout</button></footer></dialog>;
}
